### ISSUE TITLE
could you please add some document on how to write binding function for existing javascript library

### ISSUE THREAD

**Issue by davidxifeng** [elm/elm-lang.org#150]
or write a demo for it.

I want to use ProtoBuf.js in elm, but after some google, I could not find any doc on how to call js functions in Elm...

port FFI could not import function type

I looked Elm/libraries/Native/*js but I still can't get it right for now...

**Comment by Fresheyeball** [comment]
@DavidFeng I too would like to use protocol buffers with Elm. Did you have any luck? Is there an old sample I can see?
