### ISSUE TITLE
Adopt F#'s composition operators << and >> instead of .

### ISSUE THREAD

**Issue by theburningmonk** [elm/elm-lang.org#158]
Similar to how you opted for the F# pipes `|>` and `<|` over Haskell's `$` operator, I think F#'s composition operators `<<` and `>>` would make code more intuitive as mentally you're 'following the arrows' instead of having to make the connection whenever you see `.`

So the step function in the mario example for instance, would read:
`step (t,dir) = physics t << walk dir << gravity t << jump dir`
instead of
`step (t,dir) = physics t . walk dir . gravity t . jump dir`

Maybe I don't spend enough time with Haskell, but `.` is associated with field access, etc. already so whenever I see `.` I have to remind myself that it's composing functions rather than a field access missing the label name. I find the F# composition operators much more intuitive as it visually signals to me that result of `jump dir` flows into `gravity t` and so on.

What do you think?

**Comment by thenikso** [comment]
I was like 

> are they insane?! that's just `.` and `$`!!" 

now I'm like

> oooooooh :open_mouth:
