### ISSUE TITLE
"A web handler threw an exception ..."

### ISSUE THREAD

**Issue by cobalamin** [elm/elm-lang.org#607]
I've seen it happen a few times, about five in total, that some page on elm-lang.org throws an exception by a web handler on loading. It's always temporary and the site renders fine on the next reload. I haven't spent that much time on the site overall, so I find a very in-your-face exception occurring five times to be a bit too much.

The error message looks like this:

```
A web handler threw an exception. Details:
gen/pages/docs/from-javascript.html: getFileStatus: does not exist (No such file or directory)
```

It has also occurred on other pages, though. It's not very predictable, but I'm able to (irregularly) reproduce by continuously refreshing some page, and it happens eventually.

**Comment by evancz** [comment]
I have observed this as well. I am not tremendously confident in the underlying Haskell server library to be bug free as more folks are using the site, so that may be the root of this. In any case, I guess this is a good thread for people to share the *specific* pages they have observed this on. Perhaps there will be a pattern!

**Comment by cobalamin** [comment]
I'm able to reproduce on `elm-lang.org/examples` (`gen/pages/examples.html`) too.

I've noticed that it also sometimes occurs that
* /assets/style.css
* /highlight/styles/default.css
* /highlight/highlight.pack.js
fail with Error 500, but don't come with any error output from the server. I've only seen these fail all together.

Sometimes both problems occur at the same time (css/js *and* the page HTML fail), but it's not always the case.

**Comment by mvtenorio** [comment]
I've seen it a few times as well. The last time on the homepage:

```
A web handler threw an exception. Details:
gen/pages/home.html: getFileStatus: does not exist (No such file or directory)
```

**Comment by JESii** [comment]
Saw it on elm-lang.org this morning; first time visited; clicked the top link from Google search. Chrome browser, Mac El Capitan.

**Comment by evancz** [comment]
We do not use a Haskell server anymore, so this should not be possible since the switch.
