### ISSUE TITLE
Please activate https for elm-lang.org

### ISSUE THREAD

**Issue by arthuredelstein** [elm/elm-lang.org#624]
Currently, elm-lang.org only allows insecure access via http. This is especially a concern as the installer executables are also only downloadable via http.

Nowadays, https is free and pretty simple with https://letsencrypt.org.

Thanks in advance!

**Comment by Ppjet6** [comment]
Is there anything I could do to help here? It pains me to see issues like this not bumped up the priority list.

**Comment by rtfeldman** [comment]
Quick note that the binaries are also available via `npm install -g elm` - and if you don't have `npm` or `yarn`, you can download tarballs of the binaries over https from https://dl.bintray.com/elmlang/elm-platform/

Not saying this shouldn't ever happen, but given that you can get the binaries via https, this doesn't seem as urgent as, say, server-side rendering. 😉

**Comment by arthuredelstein** [comment]
It looks like this website is hosted on DreamHost? Is that correct? If so, setting up a free Let's Encrypt certificate is free and extremely simple and quick:
https://help.dreamhost.com/hc/en-us/articles/216539548-How-do-I-add-a-free-Let-s-Encrypt-certificate-

**Comment by Ppjet6** [comment]
@rtfeldman, indeed putting the binaries under https is important, but it's not just what bothers me.

I think that, assuming no binaries and just static content, the privacy bit is still of valuable importance whatever the content. As technical people we should be more sensible to this, to balance with regular Joe not even knowing what "privacy" means.

I would really appreciate if you could at least consider it from this point of view.

**Comment by Ppjet6** [comment]
Just droping this here: https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

**Comment by avh4** [comment]
Yes, there are plans for this, and there is work in progress to make it happen.

**Comment by mpizenberg** [comment]
Hi, regarding this, I also recently did the transition so here it is in case useful. In my case, centos vps with nginx serving. Thanks to the work of the [Electronic Frontier Foundation (EFF)][certbot], and the [Let's Encrypt][encrypt] project it boiled down to three simple steps:

[certbot]: https://certbot.eff.org/
[encrypt]: https://letsencrypt.org/

**Step 1: installing certbot**
```shell
sudo yum install certbot
sudo yum install certbot-nginx
```

**Step 2: launch certbot interactive mode to update nginx config**
```shell
# Just follow the bot questions
sudo certbot --nginx
```

**Step 3: configure automatic certificate renewal once a day**
```shell
# Make sure everything is fine with a dry-run renewal
sudo certbot renew --dry-run

# Add a cron job
sudo crontab -e

# Inside the opened file, add the following line, save and close
*/24 * * * * certbot renew --quiet --no-self-upgrade && systemctl restart nginx
```

Done :tada:

**Comment by evancz** [comment]
Switched with the 0.19 release.
