### ISSUE TITLE
Missing pages return incorrect http response code

### ISSUE THREAD

**Issue by auxsoft** [elm/elm-lang.org#643]
Missing pages are currently returning 200 OK http response; should return 404.

**Comment by iam-peekay** [comment]
@auxsoft can you point me to where you see the missing pages? Would love a little more detail so I can help out :)

**Comment by auxsoft** [comment]
I think there is a little misunderstanding. I am drawing attention to the problem that the server is responding with an incorrect http code for resources that do not exist. Try to get any non existing page and you'll see that the http status code of the response is 200 OK.

**Comment by iam-peekay** [comment]
@auxsoft can you give me an example of a non-existent resource that is returning a 200 OK? I don't think i fully understand the problem you're having and where you are having it

**Comment by auxsoft** [comment]
@iam-peekay http://elm-lang.org/test

**Comment by iam-peekay** [comment]
@auxsoft got it. that's strange because the backend code does set the status to be 404

```
error404 :: Snap ()
error404 =
  do  modifyResponse (setResponseStatus 404 "Not found")
      serveFile (FT.file ["pages"] "404" "html")
```

good catch. we'll see if we can fix it.

**Comment by auxsoft** [comment]
No longer using the haskell backend.
