### ISSUE TITLE
Sketch-n-Sketch example no longer works

### ISSUE THREAD

**Issue by zvory** [elm/elm-lang.org#662]
This isn't a bug in elm-lang.org, but it's still an issue.

One of the examples on [elm-lang.org](http://elm-lang.org/), specifically the Sketch-n-Sketch example, does not function. The dev, on the topic of the latest version:

> This version may introduce performance issues. If the application crashes with "too much recursion," try running with a larger stack (e.g. open -a "Google Chrome" --args --js-flags="--stack-size=8192"). 

I tried it on Ubuntu/Firefox (both latest versions), on two different machines, and I got that error.

The example should probably be removed until the example works by default. Otherwise its a pretty awful demo.

**Comment by evancz** [comment]
This is no longer one of the examples listed there!
