### ISSUE TITLE
Sanitize repository-url in namespaces

### ISSUE THREAD

**Issue by hkjels** [elm/elm-lang.org#669]
Using `.` in the repository-url, except from the `.git$`-part will cause syntax-errors upon executing the code. That is, it will compile just fine, but break in the browser.
Note that using `.`'s are quite usual as github-pages require them, so I believe this issue needs to be prioritized as it can put new users off.

For clarity, the url below would fail:
`"repository": "https://github.com/user/user.github.io.git"`

I'm using Elm `0.18.0` and any modern browser will fail for any modern OS

**Comment by evancz** [comment]
I'm not clear on what this means. I think it refers to something related to `package.json` which is not needed for building the site at this time.

**Comment by hkjels** [comment]
You're probably right. I'm having a hard time grasping the issue myself 😳
Sorry

**Comment by evancz** [comment]
No worries! This repo has changed a lot over time!
