### ISSUE TITLE
A 36 char 'fold isElement' for union type examples

### ISSUE THREAD

**Issue by stegrams** [elm/elm-lang.org#687]
In [Binary Tree Example](http://elm-lang.org/examples/binary-tree) exercise 5, there is a challenge for a ```fold isElement``` shorter than 46 character.

Surprising enough (at least for me) this can be achieved in 36 characters
```elm
fold ((||) << (==) 1) False niceTree  --> True
fold ((||) << (==) 2) False niceTree  --> True
fold ((||) << (==) 3) False niceTree  --> True
fold ((||) << (==) 4) False niceTree  --> False 
```
Where each partial operator function ```(==) number``` and ```(||) bool``` gets an argument from ```fold```, the current *niceTree* member ```number``` and the previous cached result ```Bool``` respectively.

```elm
--- Type Inference from elm-repl

> ((||) << (==) 4)
--> <function:d_e_l_t_r_o_n_3_0_3_0> : number -> Bool -> Bool
```

**Comment by evancz** [comment]
Nice discovery! It looks like you beat the best version I could think of 😄

I am currently going through https://elm-lang.org/examples to try to make it reflect the modern Elm ecosystem a bit more, so I took out the code golf puzzles for now. They are fun, but I don't want the official site emphasizing that aspect.

I'm hoping to get a bunch of fun examples back though, so hopefully there'll be another fun one about trees :)

**Comment by stegrams** [comment]
@evancz in Elm I found the best version of code structure I could ever thing of. Thank you the unique and refreshing experience I ve lived coding in Elm my friend :+1:
