### ISSUE TITLE
Elm installation instructions should note libgmp-dev dependency 

### ISSUE THREAD

**Issue by JoshTGreenwood** [elm/elm-lang.org#711]
This page should mention the libgmp-dev https://guide.elm-lang.org/install.html dependency. Are there other implicit binary dependencies that should also be noted?

**Comment by KurtRMueller** [comment]
I've just been bitten by this trying to install Elm on `Centos 6.9`.

**Comment by KurtRMueller** [comment]
@JoshTGreenwood How did you eventually end up installing Elm and satisfying the `libgmp-dev` dependency?

**Comment by JoshTGreenwood** [comment]
I wish I could remember. I assumed I just used apt-get or equivalent

**Comment by andys8** [comment]
Ran into this issue too. Using alpine.

**Comment by evancz** [comment]
Using https://github.com/elm/compiler/issues/1949 as the canonical location for this general request.
