### ISSUE TITLE
Serve Elm websites over HTTPS

### ISSUE THREAD

**Issue by jimmycuadra** [elm/elm-lang.org#714]
I use the [HTTPS Everywhere](https://www.eff.org/https-everywhere) extension from the EFF, with the option to block all unencrypted requests turned on. This is normally not a big problem, because all of the websites I visit frequently are served over HTTPS. I just started learning Elm and so I've been visiting a lot of the pages on the various Elm websites, but since most of them are not served over HTTPS, I have to keep manually disabling my strict HTTPS Everywhere settings each time.

I could just disable my extension and deal with it, but I think the proper solution is for Elm's websites to be served over HTTPS. There has been a big push in the last few years to start encrypting more of the web, making HTTPS the default expectation for all sites. It's even free, now that [Let's Encrypt](https://letsencrypt.org/) is available.

I believe some (or perhaps all?) of Elm's website are hosted via GitHub pages, which currently doesn't allow HTTPS on custom domains. This is a shame, and something GitHub really needs to address. Alternatives, for the time being, are to allow access to the sites via the github.io domain, e.g. https://elm-lang.github.io/elm-lang.org/, or to simply move the hosting of the websites to another hosting platform like AWS or DigitalOcean that will allow the pages to be served over HTTPS from the elm-lang.org domain, with an automated setup for renewing the certificate(s) for free.

The sites I've noticed do not serve over HTTPS currently are:

* elm-lang.org
* package.elm-lang.org
* elm-community.org
* faq.elm-community.org
* builtwithelm.co

(The last three may not be official Elm sites, and hence this issue may need to be raised separately to whomever runs them.)

Thanks for Elm, your time, and consideration!

**Comment by kachkaev** [comment]
Also faced this problem because of the _HTTPS Everywhere_ extension in FF. Shame that github pages still lack HTTPS out of box. The feature request has been out there for three years: https://github.com/isaacs/github/issues/156.

Seem like the only workaround for now is to use a service like CloudFlare. Instructions can be found in https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

**Comment by andys8** [comment]
If the pages are github pages, like foundation.elm-lang.org let's encrypt can be used: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by ayosec** [comment]
It seems that both https://elm-lang.org/ and https://package.elm-lang.org/ have HTTPS enabled.

A few suggestions to have a more complete support for HTTPS:

* Redirect http://elm-lang.org/ to https://elm-lang.org/.
    * This is already done for  http://package.elm-lang.org/
* Set [HTTP Strict Transport Security](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) in the responses.
* Submit both domains to https://hstspreload.org/

**Comment by evancz** [comment]
I recently updated https://elm-lang.org/ and https://package.elm-lang.org/ to work over HTTPS so I will close the root issue. I do not know about the other ones.
