### ISSUE TITLE
Online Editor still using Core 5.0.0

### ISSUE THREAD

**Issue by evanshort73** [elm/elm-lang.org#742]
I discovered this by entering the following code:
```elm
import Html exposing (text)

main =
  text <|
    case String.toFloat "1e-5" of
      Ok x -> toString x
      Err e -> e
```
and getting the response "could not convert string '1e-5' to a Float"

In Core 5.0.0, strings involving exponents could not be converted to floats, but in 5.1.0 and 5.1.1 they can.

To double check, I examined the Online Editor's js files in my browser and searched for the text "to a Float". I discovered a file called `compile` which contained the exact source code of `Native.String.toFloat` from Core 5.0.0

**Comment by evancz** [comment]
The `/try` page is down for now. When it comes back, it'll have the latest version of things.
