### ISSUE TITLE
Broken link in blog

### ISSUE THREAD

**Issue by PericlesTheo** [elm/elm-lang.org#753]
Hey 👋

The _[Concepts behind the Elm Logo](https://github.com/elm-lang/elm-lang.org/blob/master/src/pages/blog.elm#L32)_ link seems to be broken

**Comment by evancz** [comment]
It should be working now. I think prezi links have a lifetime if you create them in certain ways, so it would close people out after some time. I switched it to be really permissive about who can view it, so hopefully it'll stay working!
