### ISSUE TITLE
LOC at NoRedInk 

### ISSUE THREAD

**Issue by ShalokShalom** [elm/elm-lang.org#769]
The homepage links to this blog post: http://elm-lang.org/blog/blazing-fast-html-round-two

It mentions 36k lines at NRI, while the homepage speaks about 80k

You might like to edit this, who knows? :D

**Comment by evancz** [comment]
The posts have dates, so I think it's best to just leave it as it was on the publication date. Otherwise you have to change it forever, which is nice in some ways but bad in others.

**Comment by ShalokShalom** [comment]
Hi Evan. I appreciate your response time and your proper understanding of how to avoid confusion about insight into your language. Good luck!
