### ISSUE TITLE
Broken Markdown on Community page

### ISSUE THREAD

**Issue by kraai** [elm/elm-lang.org#771]
The Community page contains the following text:

```
It is the successor to [elm-discuss on Google Groups][list].
```

This appears to have been caused by bc865c6e5311cbed43c78309d4f8564f00e66124, which removed the definition of `list`.

Here are the options I can think of for fixing this:

* Remove this sentence.
* Fix the link.
* Remove the link but leave the sentence.

**Comment by evancz** [comment]
That line has been removed!
