### ISSUE TITLE
package.elm-lang.org returns a 404 status code when trying to see latest version of package

### ISSUE THREAD

**Issue by MightyAlex200** [elm/elm-lang.org#780]
`/packages/name/package/latest` on `package.elm-lang.org` always returns a 404, even when everything else appears to be working fine.

**Comment by evancz** [comment]
Can you show an example of this? I do not really get what you are talking about. Maybe just say more about how to make this happen or do some tests with slowing down the network speed in dev tools and tell me what you find out.

**Comment by MightyAlex200** [comment]
Sorry, I should have been more clear,
Steps to reproduce:
1. Go to `package.elm-lang.org/packages/(name)/(package)/latest` (replacing `(name)` and `(package)` with their respective strings e.g. `elm/core`)
2. Open network tab of devtools (have tested on Chrome and Firefox)
3. Refresh
4. The request to `latest` returned a 404 status code, regardless of actual page content

Here is a screenshot:
![image](https://user-images.githubusercontent.com/12374063/44564741-9e400800-a732-11e8-918d-44182929d231.png)

**Comment by evancz** [comment]
Thanks for the clarification. I'll look into it!

**Comment by evancz** [comment]
Should be fixed now. Thanks for the report!
