### ISSUE TITLE
DNS cannot resolve the server with the examples

### ISSUE THREAD

**Issue by lykahb** [elm/elm-lang.org#784]
DNS cannot resolve the server with the examples [http://try.elm-lang.org/examples/buttons](http://try.elm-lang.org/examples/buttons)

**Comment by evancz** [comment]
Got the examples working again: https://elm-lang.org/examples

With 0.19 we switched the website to netlify, so there wasn't any server to run the compiler on anymore. Recently got a server back up that can handle all the `Compile` requests for `/try` and `/examples`.

**Comment by wrg1977** [comment]
site ; python -m SimpleHTTPServer 8000
