### ISSUE TITLE
http://try.elm-lang.org/ is down

### ISSUE THREAD

**Issue by AdrianRibao** [elm/elm-lang.org#786]
Not sure if this issue belongs to this project, but I couldn't find a better place.

It looks like http://try.elm-lang.org/ is down

**Comment by Taskkill** [comment]
Can confirm https://downforeveryoneorjustme.com/try.elm-lang.org

**Comment by evancz** [comment]
I updated some redirects to try to explain the situation. If you find specific links on the site that are broken, please share a link to the specific page that has the broken link in a new issue.
