### ISSUE TITLE
Community Page > Meetups Link needs replaced

### ISSUE THREAD

**Issue by pootsbook** [elm/elm-lang.org#793]
I used to maintain a list of meetups on https://www.elmlog.com/meetup_groups

Due to other priorities I do not have the bandwidth to maintain the page or keep the servers running.

**The link to Meetups (see screenshot) on the Community page should be updated** and potentially even a new page created on the website using the data below.

![Elm website, Community Page, Meetups Link](https://user-images.githubusercontent.com/35313/48128073-b16c6980-e285-11e8-9884-6c8bf0a32f2f.png)

### Meetup Data

(As of 2018-11-07)

<details>
  <summary>meetups.csv</summary>
  <pre>
Name,MeetupID,MeetupURL
Elm user group SF,10027652,Elm-user-group-SF
Elm User Group Dublin,19111172,Elm-User-Group-Dublin
Elm Warsaw,19328995,Elm-Warsaw
Tokyo Elm Programming Meetup,19340761,Tokyo-Elm-Programming-Meetup
Boston Elm,19638661,Boston-Elm
Portland Elm Group,19562037,portlandelm
Elm Copenhagen,18964444,Elm-Copenhagen
ElmShop - Dallas Elm Web Programming Workshop,19651237,ElmShop
Sydney Elm Meetup,19806846,Sydney-Elm-Meetup
Boston Elm Lang Meetup,19426879,Boston-Elm-Lang-Meetup
Elm User Group DC,19689914,Elm-User-Group-DC
Elm London Meetup,19484113,Elm-London-Meetup
STL Elm,19086914,STLElm
Elm NYC,19329611,Elm-NYC
Stockholm Elm,19461183,Stockholm-Elm
Seattle Elm,19611555,Seattle-Elm
Meetup Elm Paris,19539779,Meetup-Elm-Paris
Chicago Elm,19148628,chicago-elm
Utah Elm Users,18886697,Utah-Elm-Users
Vienna Elm Meetup,19157470,Vienna-Elm-Meetup
Elm Berlin,19752364,Elm-Berlin
Elm - TLV,19111791,Elm-TLV
Elmsinki,19359022,Elmsinki
Berlin Elm-Hackathon,18796859,berlin-elm-hackathon
Elm Wellington,19566821,Elm-Wellington
Elm Zürich,19788454,Elm-Zurich
Elmoin,19826316,Elmoin
Oslo Elm Meetup,19885965,oslo-elm-meetup
Brno Elm Meetup,19886319,Brno-Elm-Meetup
Elm Meetup Munich,19943573,Elm-Meetup-Munich
Elm Portland (Maine),19889967,Elm-Portland-Maine
Hangzhou Elm Meetup,19830122,Hangzhou-Elm-Meetup
Elm user group Vancouver,19910514,Elm-user-group-Vancouver
Denver Elm Developers,20017311,Denver-Elm-Developers
Elm Netherlands,20106753,Elm-Netherlands
Elm user group Boulder,20205344,Elm-user-group-Boulder
Elm Amsterdam,20159308,Elm-Amsterdam
Atlanta Elm Users Group,20325781,Atlanta-Elm-Users-Group
Istanbul Elm Meetup,20484004,elm-istanbul
Elm DC,20508505,Elm-DC
Elm Orlando,20311906,ElmOrlando
Meetup Elm Brussels,20331361,Meetup-Elm-Brussels
Elm Cambridge,20231140,elm-cambridge
Elm Taipei Meetup,20171425,Elm-Taipei-Meetup
Elm Melbourne,20621798,Elm-Melbourne
Bogazici University Elixir & Elm Meetup,20722182,Bogazici-University-Elixir-Elm-Meetup
Elmlang Las Vegas,20919414,Elmlang-Las-Vegas
Elm Gothenburg,22685120,Elm-Gothenburg
Elm Kansas City,21634590,Elm-Kansas-City
Elixirlang Delhi NCR,20271402,Elixirlang-Delhi-NCR
Lille FP,19012149,Lille-FP
Elm SP,22218769,Elm-sp
ElmPrague,22896354,ElmPrague
Elm Stuttgart,24424845,Elm-Stuttgart
Elm Philadelphia,25255943,Elm-Philadelphia
Elm user group Cologne,22484936,Elm-user-group-Cologne
Elm Toronto,21588285,Elm-Toronto
Elm Brisbane,30326721,Elm-Brisbane
Elm Meetup Leipzig,23802430,Leipzig-Softwareentwicklung-Meetup
  </pre>
</details>

**Comment by ashishsc** [comment]
This is also an issue on the [elm guide](https://guide.elm-lang.org/next_steps.html)

**Comment by evancz** [comment]
I have a different link on my local version of things, so it'll be fixed when that is done. Want to close now while I am looking at this though!
