### ISSUE TITLE
Why does grammar enforce continuity？

### ISSUE THREAD

**Issue by allphfa** [elm/elm-lang.org#795]
For example, Add as C; end the let statement, after let in

I can't understand this kind of grammar. Let in should be a statement. Case XX of is similar to switch statement, but why can't compile it?
```
update: msg -> model

    let a = 1 in a

    case msg of xx ->
        ....
```

**Comment by evancz** [comment]
We try to keep issues more about bugs. Learning happens more in community forums, so I recommend asking on https://discourse.elm-lang.org/ or https://elmlang.herokuapp.com/ where folks can give direct feedback. If you go to the Slack, I believe there is a #beginners channel that could probably help!
