### ISSUE TITLE
Old info: Record update syntax doesn't allow type change

### ISSUE THREAD

**Issue by malaire** [elm/elm-lang.org#796]
`src/pages/docs/records.elm` talks about how "You can even change the type of value in a field" in section "Updating Records".

This isn't true anymore in Elm 0.19

**Comment by Munksgaard** [comment]
It also lists the following example which is not valid in 0.19:

```elm
rawInput =
  { name = "Tom"
  , country = "Finland"
  , age = "34"
  , height = "1.9"
  }

prettify person =
  { person |
      age = String.toInt person.age,
      height = String.toFloat person.height
  }

input =
  prettify rawInput

```

**Comment by LiberalArtist** [comment]
For anyone stumbling across this, [here is the part of the 0.19 release note](https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md#stricter-record-update-syntax) that explains this is no longer allowed.
