### ISSUE TITLE
Javascript Section in .elm File

### ISSUE THREAD

**Issue by riiccardo** [elm/elm-lang.org#800]
For those who want to use **`npm packages`** **`just with import`** **`not with the CDN link or link scripts in .html file`** in their project

please add this feature

for example if u go to [Elm Packages](https://package.elm-lang.org/) you can't find these Plugins ⬇️ 

for example a Carousel like : `Glide.js`, `OwlCarousel`, `Slick`, `Swiper`, ....

or Animation library like : `anime.js`, `Gasp`, `Velocity`, ....

```elm
-- not real code just example

module Main exposing (..)


-- npm packages
import Glide from 'glide.js'

import Html exposing (..)
import Html.Attributes exposing (..)

-- javascript code
javascriptModel : [
   const glide = new glide('.glide', {
       -- glide options
  })
]


view : Model -> Html Msg
view model =
-- not real code just example
  div []
       [ h1 [] [ text "Carousel" ]
        , div [ class "carousel" ]
        [ div [ class "carousel-cell" ]
                 []
          , div [ class "carousel-cell" ]
                 []
          , div [ class "carousel-cell" ]
                 []
           , div [ class "carousel-cell" ]
                  []
           , div [ class "carousel-cell" ]
                  []
            ]
]

```

**Comment by evancz** [comment]
This sort of suggestion has been subject to a great deal of discussion, partly summarized [here](https://discourse.elm-lang.org/t/native-code-in-0-19/826), and there are not plans to add something like this to the language.
