### ISSUE TITLE
Unable to open "Text Fields" section

### ISSUE THREAD

**Issue by gotschmarcel** [elm/elm-lang.org#806]
Navigation to the "Text Fields" section is not working. Neither via the right-arrow button on the right side of the page nor via the sidebar navigation. Accessing the page directly from Google also doesn't seem to work.

![elm_lang_org_section_broken](https://user-images.githubusercontent.com/4235955/55113004-414c6c00-50de-11e9-8fff-b180a94de016.gif)

**Comment by evancz** [comment]
I'm able to open it with no problem:

![Screen Shot 2019-04-04 at 3 24 46 PM](https://user-images.githubusercontent.com/1658058/55582563-d73f5280-56ed-11e9-89d1-0cd5ce0ccc1f.png)

The issue you are seeing may be related to:

1. OS
2. Browser
3. Transient issues with gitbook

Or something else. So without further information, it is unclear how to pursue this.

**Comment by gotschmarcel** [comment]
I tested in in Firefox, Chrome & Safari on MacOS Mojave, but all didn't work. Anyways the issue seems to be fixed.

**Comment by evancz** [comment]
Weird! Perhaps gitbook was testing an alternate implementation of things or something. Anyway, thanks for reporting, and glad it's working again!
