### ISSUE TITLE
0.19 documentation - Imports' snippet showcases invalid syntax

### ISSUE THREAD

**Issue by reaysawa** [elm/elm-lang.org#811]
https://elm-lang.org/0.19.0/imports#default-imports

---

### Quoting

It would be the best policy to make it so every module in the whole ecosystem works this way. We thought so in the past at least, but there are some modules that are so commonly used that the Elm compiler automatically adds the imports to every file. These default imports include:

```
import Basics exposing (..)
import List exposing ( List, (::) )
import Maybe exposing ( Maybe( Just, Nothing ) )
import Result exposing ( Result( Ok, Err ) )
import String
import Tuple

import Debug

import Platform exposing ( Program )
import Platform.Cmd as Cmd exposing ( Cmd )
import Platform.Sub as Sub exposing ( Sub )
```

### In the code

```
Something went wrong while parsing an import.

4| import Maybe exposing ( Maybe( Just, Nothing ) )
                                  ^
I was expecting to see the (..) symbol.
```

**Comment by evancz** [comment]
Nice catch! I just made some edits that'll come out with 0.19.1. Thanks!
