### ISSUE TITLE
bad slack link

### ISSUE THREAD

**Issue by decapo01** [elm/elm-lang.org#812]
The slack link in the community section of the site leads to

http://elmlang.herokuapp.com/

instead of https://elmlang.slack.com

**Comment by decapo01** [comment]
Ok sorry silly me.  What's throwing me off is that it's not an https site that you are linking too so I see a nonsecure notification.  But you are just entering in your email address here so not too big of a deal.

**Comment by evancz** [comment]
It should be going to the HTTPS version now! Thanks for the recommendation!
