### ISSUE TITLE
Broken noredink link

### ISSUE THREAD

**Issue by mfdavid** [elm/elm-lang.org#813]
The noredink logo on the front page points to: http://tech.noredink.com/post/129641182738/building-a-live-validated-signup-form-in-elm

But all we get is a "There's nothing here" page.

**Comment by evancz** [comment]
It appears to be working now. Maybe their blog server was down for a bit!

I'm also revamping the home page, so when a link gets added for NRI again it'll be to a "user experience" type post instead.
