### ISSUE TITLE
Example thwomp breaks on compile

### ISSUE THREAD

**Issue by ni-ko-o-kin** [elm/elm-lang.org#815]
regarding https://elm-lang.org/examples/thwomp

The example works when I load the page but when I press compile I only see 'Loading textures...' and in the console I see this error:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin 

Same here: https://elm-lang.org/examples/first-person

**Comment by evancz** [comment]
It should be fixed by https://github.com/elm/elm-lang.org/commit/c2cdadb1ae16435c2bca6d405c38db7e82aa4ad3. I am seeing it work in my browser now at least.

Thank you for reporting this, and please let me know if you notice other problems like this!

**Comment by ni-ko-o-kin** [comment]
I can confirm, it works!
