### ISSUE TITLE
Trying to install using yarn

### ISSUE THREAD

**Issue by marcoanicosta** [elm/elm-lang.org#818]
Trying to install language-elm using `apm install language-elm`, but not sure what the command is for elm originally tried `yarn add langauge-elm` to get the below issue. Any ideas?

```[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/language-elm: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/marcoanicosta/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.```

**Comment by evancz** [comment]
Are you trying to install Elm on your computer?

If so, I recommend using the options listed [here](https://guide.elm-lang.org/install.html).

I recommend asking around in the Elm slack [here](https://elmlang.herokuapp.com/) if you have further questions. People there will probably know more than me about yarn.
