### ISSUE TITLE
Unable to click on any link on elm-lang.org (weird)

### ISSUE THREAD

**Issue by js-d-coder** [elm/elm-lang.org#819]
Okay, this may sound very weird but I am not able to click any link on elm-lang.org, except on top nav bar. I am attaching a picture for proof. They all appear as normal text element but when I inspect it I can see `a` tag.

I am using Brave (Version 0.67.119 Chromium: 76.0.3809.72 (Official Build) unknown (64-bit)) and have disabled its built-in adblock called Brave Shield. But don't have this problem on Firefox Developer Edition v68. Brave is my default browser.

Thanks

![Screenshot_20190917_212844](https://user-images.githubusercontent.com/23054879/65058721-566dcd80-d992-11e9-982d-d041eb5bc892.png)

**Comment by theianjones** [comment]
Im experiencing similar issues. I reported it on [Twitter](https://twitter.com/_jonesian/status/1306046155915132933) as well.

![Screen Recording 2020-09-16 at 10 06 AM](https://user-images.githubusercontent.com/4407263/93348863-c19beb00-f804-11ea-85ea-b7136266e873.gif)

<img width="1327" alt="Image 2020-09-15 at 9 43 28 PM" src="https://user-images.githubusercontent.com/4407263/93348881-c6f93580-f804-11ea-87c5-3e90254e4f88.png">

**Comment by js-d-coder** [comment]
I am happy to acknowledge after waiting for a year to have a fix simple on static website, this framework isn't going anywhere!!!
