### ISSUE TITLE
Link to learning resouses on elm-lang.org resolves to eror 404

### ISSUE THREAD

**Issue by dratushnyy** [elm/elm-lang.org#823]
How to reproduce:
Open a URL "https://elm-lang.org/docs/syntax", right after the table of context, there is a small paragraph, containing a link named "Learning resources" and pointing to URL "https://elm-lang.org/Learn.elm". Click on the link

Expected result:
A user is navigated  to a page with a list of learning resources

Actual result:
Error 404.

This issue is very discouraging, especially for newcomers.

**Comment by evancz** [comment]
Thanks for the report! The fixed link should be live now!
