### ISSUE TITLE
elm init page 404

### ISSUE THREAD

**Issue by eimfach** [elm/elm-lang.org#840]
After I started a new Elm Project with `elm init` the output refers to the init documentation for 0.19.1:

`Check out <https://elm-lang.org/0.19.1/init> for all the answers!`

-> which redirects me to the following link in elm compiler repository:

https://github.com/elm/compiler/blob/master/hints/init%3E.md

-> Which leads me to the 404 Page of GitHub

I guess something went wrong, since there is this `%3E` character ...

**Comment by rlefevre** [comment]
What OS, shell and terminal do you use?

For me, clicking in my terminal the link opens https://github.com/elm/compiler/blob/master/hints/init.md which works correctly.

**Comment by eimfach** [comment]
Oh okay yes, I see... when I opened it manually it works.
I am using macOS and open the link with cmd+click from vscode terminal...

**Comment by rlefevre** [comment]
Then your terminal includes the `>` in the URL, trying to open https://elm-lang.org/0.19.1/init>.
Maybe it would be better to remove the enclosing `<` and `>` in terminal URLs to avoid this.
