### ISSUE TITLE
delete account on discourse?

### ISSUE THREAD

**Issue by vsoch** [elm/elm-lang.org#854]
Hi Elm! I suspect this is the wrong place to post it, but I'm looking for a contact for how to delete my account on https://discourse.elm-lang.org/. I looked in preferences and didn't see anything, and I don't see a topic board there to talk about account related things. I went to the main site and found the GitHub here, and am hoping this can give me a pointer in the right direction. Sorry for the noise!

**Comment by BrianHicks** [comment]
hi @vsoch, I can take care of that for you. Would you please message me on Discourse (I'm @brian there) just to demonstrate control of the account? Once we confirm that, I'll go ahead and deactivate your account.

**Comment by vsoch** [comment]
All set, thank you!
