### ISSUE TITLE
The landing page is quite user hostile

### ISSUE THREAD

**Issue by ad-si** [elm/elm-lang.org#863]
Many people (including me) buy large 4k screens to see more content. However, since the landing page scales to whatever screen size you have, it's basically like saying "F*** you and your large screen, I'm not going to show you any more content".  It's especially pronounced for screens rotated to portrait mode.

Can we please give the first section a maximum height?

**Comment by terezka** [comment]
Sure, thank you for your feedback! :)

**Comment by terezka** [comment]
Fixed with https://github.com/elm/elm-lang.org/commit/e943fdaea105c740919cbeeed56473726bb374e9.

**Comment by ad-si** [comment]
Thanks @terezka for the fast response! However, it's not working yet. The `min-height` seems to overwrite the `max-height`. Converting the `min-height` to a `height` seems to yield the correct results.

**Comment by terezka** [comment]
Oh, sorry! As you have probably guessed, I don't have a monitor myself, so it was tricky to test! 😬 I'll just check the screen size then and add the height instead. Thanks for getting back to me!

**Comment by terezka** [comment]
Should be up now if you want to check it out! Let me know if you still find it too tall.

Hopefully fixed with https://github.com/elm/elm-lang.org/commit/a123ed9495e64c5dafba2660032ae28cc39af8f7.

**Comment by ad-si** [comment]
Yes, much better! Thanks! 😊
